# Generated by Django 4.1.8 on 2023-05-02 20:58

from django.db import migrations, models
import utils.commons


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_friendrequest_friendrequest_unique_friend_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.commons.UniqueFilename('avatars/')),
        ),
        migrations.AlterField(
            model_name='user',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to=utils.commons.UniqueFilename('headers/')),
        ),
    ]
